---
sudo: required
language: python
services:
  - docker
python:
  - "3.8"
env:
  matrix:
    - SCENARIO_NAME=debian-stretch-vanilla-fixversion
    - SCENARIO_NAME=debian-buster-vanilla-fixversion
    - SCENARIO_NAME=debian-bullseye-vanilla-fixversion
    - SCENARIO_NAME=debian-xenial-vanilla-fixversion
    - SCENARIO_NAME=debian-bionic-vanilla-fixversion
    - SCENARIO_NAME=redhat-centos7-vanilla-fixversion
    - SCENARIO_NAME=redhat-centos8-vanilla-fixversion
    - SCENARIO_NAME=redhat-twentyNine-vanilla-fixversion
    - SCENARIO_NAME=debian-stretch-spigot-fixversion
    - SCENARIO_NAME=debian-buster-spigot-fixversion
    - SCENARIO_NAME=debian-xenial-spigot-fixversion
    - SCENARIO_NAME=debian-bionic-spigot-fixversion
    - SCENARIO_NAME=redhat-centos7-spigot-fixversion
    - SCENARIO_NAME=redhat-twentyNine-spigot-fixversion
    - SCENARIO_NAME=debian-bionic-spigot-latest
    - SCENARIO_NAME=redhat-centos7-spigot-latest
    - SCENARIO_NAME=redhat-twentyNine-vanilla-latest
    - SCENARIO_NAME=plugins
    - SCENARIO_NAME=docs
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
install:
  - pip install tox-travis
script:
  - tox -e ${SCENARIO_NAME}

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

branches:
  only:
    - master
    - develop
    - feature/*
    - fix/*
