---
- name: install Minecraft dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependencies }}"

- name: install Spigot dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - git
    - tar
  when: minecraft_server == 'spigot'
