---
- name: Add symlinks from the new release to the shared folder
  file:
    dest: "{{ deploy_helper.shared_path }}/spigot.jar"
    src: "{{ deploy_helper.current_path }}/spigot-{{ minecraft_version_int }}.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  notify:
    - restart Minecraft

- name: Add plugins symlinks to the shared folder
  file:
    dest: '{{ deploy_helper.shared_path }}/plugins'
    src: '{{ minecraft_plugins }}/shared'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  notify:
    - restart Minecraft
  when: minecraft_plugin_sets is defined and minecraft_plugin_sets|length>0
